import type { NextPage } from "next";
import { useState, useEffect } from "react";
// NextJS components:
import Head from "next/head";
// Custom components:
import { Weather } from "./components/Weather";
import { Header } from "./components/Header";
import axios from "axios";

const Home: NextPage = () => {
  // User Location:
  const [lat, setLat] = useState<number>(0);
  const [long, setLong] = useState<number>(0);
  useEffect(() => {
    const geolocationAPI = global.navigator.geolocation;
    const getUserLocation = () => {
      if (!geolocationAPI) {
        console.log("FUCK");
      } else {
        geolocationAPI.getCurrentPosition((position) => {
          const { coords } = position;
          setLat(coords.latitude);
          setLong(coords.longitude);
        });
      }
    };
    getUserLocation();
    changeBtnName();
  });

  // Fetch the weather:
  const [weather, setWeather] = useState<any>({});
  const url: string = `https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${long}&appid=${process.env.NEXT_PUBLIC_API_KEY}&units=metric`;
  const fetchWeather = () => {
    axios.get(url).then((response: any) => {
      setWeather(response.data);
    });
  };

  console.log(weather);

  // Fetch/Refresh btn func:
  const [btn, setBtn] = useState<string>("Fetch weather");
  const changeBtnName = () => {
    if (Object.keys(weather).length > 0) {
      setBtn("Refresh");
    }
  };

  return (
    <div className="flex w-full h-screen justify-evenly items-center bg-treesBg flex-col ">
      <Head>
        <title>The Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header city={weather.name} country={weather.sys?.country} />
      <main className="outline outline-2 outline-red-300 w-3/4">
        <Weather
          temperature={weather.main?.temp}
          feelsLike={weather.main?.feels_like}
          sunrise={weather.sys?.sunrise}
          sunset={weather.sys?.sunset}
          wind={weather.wind?.speed}
          weatherShort={weather.weather?.[0].main}
          weatherDesc={weather.weather?.[0].description}
        />
      </main>
      <button
        className="rounded-full border-solid border-4 border-slate-50 px-1 py-1 backdrop-blur"
        onClick={fetchWeather}
      >
        <span className="bg-slate-50 rounded-full w-11/12 h-screen px-5 py-1">
          {btn}
        </span>
      </button>
      <footer className="flex justify-center w-full absolute bottom-0 bg-orange-200 pl-1 text-xs">
        <p>The weather app by </p>
        <a href="https://github.com/rockysfairat" className="ml-1 underline">
          Ålexander Yurchenko
        </a>
      </footer>
    </div>
  );
};

export default Home;
